apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
  namespace: qaq-dev
  labels:
    app: demo-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-server
      version: v1
  template:
    metadata:
      labels:
        app: demo-server
        version: v1
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: demo-server
          image: hub.bilibili.co/lifajin/demo-server:1.0.1
          imagePullPolicy: Always
          command: ['java']
          args:
            - -jar
            - -Duser.timezone=GMT+8
            - demo-server.jar
            - --spring.profiles.active=dev
          ports:
            - containerPort: 9999
