apiVersion: v1
kind: Service
metadata:
  name: demo-server
  namespace: qaq-dev
  labels:
    app: demo-server
    service: demo-server
spec:
  selector:
    app: demo-server
  ports:
    - name: http
      port: 80
      targetPort: 9999